version: "3"
services:
  echo:
    build: .
    image: ${repository}:echo-1.0-alpine-8000
    container_name: echo
  curl:
    container_name: curl
    image: curlimages/curl
    command: 
      - sh
      - -c
      - while true; do date; sleep 60; done
